## Функции. Рекурсия.


### Упражение 1
Написать функцию, считающую N-ое число Фибоначчи (N вводится с клавиатуры).

### Упражение 2
Написать функцию, раскладывающую число на простые множители (число вводится с клавиатуры).


### Упражнение 3
Со времен Евклида известно, что для любых положительных a и b существуют такие целые x и y, что ax + by = d, где d – наибольший общий делитель a и b. По заданным a и b найти x, y, d.

Вход. Каждая строка содержит два натуральных числа a и b, разделенных пробелом.

Выход. Для каждой пары a и b в отдельной строке вывести три целых числа x, y и d, разделенных пробелом. Если искомых значений x и y несколько, то следует выводить такую пару, для которой |x| + |y| минимально. Если и таких пар несколько, то вывести ту пару, в которой x минимально.

|Пример входа|Пример выхода|
|-|-|
|4 6|-1 1 2|
|17 17|0 1 17|
|5 3|-1 2 1|



### Упражнение 4
Напишите функцию для вывода треугольника. Функция принимает два аргумента – size (количество строк, на которых будет строиться треугольник) и symb (символ, используемый для заполнения треугольника).

Пример входа: `7 c`

Пример выхода:
![image-2.png](attachment:image-2.png)



 

In [15]:
! pip help install

# обращение в командной строке jupyter


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

Description:
  Install packages from:
  
  - PyPI (and other indexes) using requirement specifiers.
  - VCS project urls.
  - Local project directories.
  - Local or remote source archives.
  
  pip also supports installing from "requirements files", which provide
  an easy way to specify a whole environment to be installed.

Install Options:
  -r, --requirement <file>    Install from the given requirements file. This
                              option can be used multiple times.
  -c, --constraint <file>     Constrain versions using the given constraints
                              file. This option can be used multiple times.
  --no-deps                   Don't install p

In [12]:
#пример с семинара
def function2(**kid):
    print("His name is " + kid["lname"])
    print("His name is " + kid["fname"])
    
function2(fname="Emil", lname="Tobias")

His name is Tobias
His name is Emil


In [92]:
#B - матрица, пример с семинара
B = np.array([0, 1, 2, 3, 4 , 5])
B = B.reshape(3,2)
print(B)
print()

print(B[1:2])
print()

print(B[1::])

[[0 1]
 [2 3]
 [4 5]]

[[2 3]]

[[2 3]
 [4 5]]


### Упражение 1
Написать функцию, считающую N-ое число Фибоначчи (N вводится с клавиатуры).

In [9]:
def fibonacci(n):
    if n == 1:
        return 0
    if n in (2, 3):
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)
 

print(fibonacci(int(input())))

6
5


In [20]:
def prime_multipliers(n):
   i = 2
   prime_numbers = []
   while i ** 2 <= n:
       while n % i == 0:
           prime_numbers.append(i)
           n = n / i
       i = i + 1
   if n > 1:
       prime_numbers.append(n)
   return prime_numbers


prime_multipliers(72)

[2, 2, 2, 3, 3]

### Задача 4

In [33]:
def triangle(size, symb):
    for i in range(1, size + 1):
        minimum = min(i, size - i + 1)
        print(symb * minimum)

data = list(input().split())
size, symb = int(data[0]), str(data[1])
triangle(size, symb)

7 c
['7', 'c']
c
c
cc
ccc
cccc
ccc
cc
c


In [96]:
numbers = list(map(int, input().split()))
x, y = numbers[0], numbers[1]


def NOD(a, b):
    while a != 0 and b != 0:
        if a > b:
            a = a % b
        else:
            b = b % a
    return (a + b)

x1 = x / NOD(x, y)
y1 = y / NOD(x, y)
x_min = int(min(x1, y1))
y_max = int(max(x1, y1))

ans_1 = y_max % x_min
if ans_1 == 0:
    ans_1 = 1
    ans_2 = 0
else:
    ans_2 = ans_1 - x_min

print(ans_2, ans_1, NOD(x, y))


4 6
-1 1 2


##### 

In [ ]:
# метод наименьших квадратов 

def mnk(x, y):
    
    size = len(x)
    
    vector = np.empty((2, 1))
    vector[0] = sum((x[i]*y[i]) for i in range(0, size))
    vector[1] = sum((y[i]) for i in range(0, size))
    
    matrix = np.empty((2, 2))
    matrix[[0], [0]] = sum((x[i])**2 for i in range(0, size))
    matrix[[0], [1]] = sum(x)
    matrix[[1], [0]] = sum(x)
    matrix[[1], [1]] = size
    
    opposite = np.linalg.inv(A)
    
    ab = np.dot(opposite, vector)
    a = ab[0]
    b = ab[1]
    
    return a, b

In [123]:
import numpy as np

def solver(N, M):
    
    N = int(input())
    M = int(input())
    arr = np.zeros((N, M))
    vector = np.zeros(N)
    matrix = np.zeros((N, M - 1))
    
    for i in range(N):
        arr[i] = list(input().split())
        matrix[i] = arr[i][:-1]
        vector[i] = arr[i][-1]
    
    return np.linalg.solve(matrix, vector)

print(solver(2, 3))

2
3
2 5 1
1 -10 3
[ 1.  -0.2]


In [75]:
s = input().split()
n, m = int(s[0]), int(s[1])
matrix = [[0 for i in range(m)] for i in range(n)]
matrix[0][0] = 1

x, y = 0, 0
destination_x, destination_y = 0, 1
value = 2

while value <= n * m:
    if (0 <= x + destination_x <= n - 1 
            and 0 <= y + destination_y <= m - 1 
            and matrix[x + destination_x][y + destination_y] == 0):
        matrix[x + destination_x][y + destination_y] = value
        value += 1
        x += destination_x
        y += destination_y

    else:
        if destination_y == 1:
            destination_y, destination_x = 0, 1
        elif destination_x == 1:
            destination_x, destination_y = 0, -1
        elif destination_y == -1:
            destination_y, destination_x = 0, -1
        elif destination_x == -1:
            destination_x, destination_y = 0, 1

for i in range(n):
    for j in range(m):
        print(str(matrix[i][j]).ljust(3), end=" ")
    print()

5 6
1   2   3   4   5   6   
18  19  20  21  22  7   
17  28  29  30  23  8   
16  27  26  25  24  9   
15  14  13  12  11  10  


### Задание 8 

Реализуйте функцию, генерирующую набор данных размером N, которые методом МНК аппроксимируются прямой с коэффициентами a и b. Для этого вам пригодится библиотека random и функция random.gauss().

In [128]:
import random
def datasets(a, b):
    
    data_size = random.randint(100, 300)
    x = np.arange(0, data_size, 1.)
    delta = np.empty((data_size, 1))
    y = np.empty((data_size, 1))
    sigma = random.uniform(1, 10)
    
    mu = 0.0 # допустим

    for i in range(data_size):
        delta[i] = random.gauss(mu, sigma)
        y[i] = a + b*x[i] + delta[i]
        
    return x, y


datasets(2, 6)


(array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
         44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
         55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
         66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
         77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
         88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
         99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
        110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
        121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
        132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
        143., 144., 145., 146., 147., 

## 